import React, {useEffect, useState} from 'react';
import {ArrowLeft, Download, FileSpreadsheet, FolderOpen, LoaderCircle, Pause, Play, Plus, RefreshCw, Upload, X} from 'lucide-react';
import './batch.css';
import {ExportDirectoryPicker} from './ExportDirectoryPicker';

type Project = {id:string;name:string;settings:Record<string,any>};
type Row = {url:string;title:string;settings:Record<string,any>;settingsText:string;row?:number};
type Item = {id:string;position:number;project_id:string;url:string;title:string;state:string;progress:number;message:string;error:string;attempts:number;ready_at:number;retry_limit:number;export_state:string;export_progress:number;export_error:string;export_message:string;export_folder:string;exports:{file:string;part:number}[]};
type Batch = {id:string;name:string;state:string;created:number;items:Item[]};
type Preview = {row:number;url:string;valid:boolean;error:string};

async function request<T>(path:string, options:RequestInit={}):Promise<T>{
  const response=await fetch('/api'+path,{...options,headers:{'X-AIR3view':'studio',...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});
  const body=await response.json();
  if(!response.ok){
    if(response.status===404&&path.startsWith('/batches'))throw new Error('Dịch vụ AIR3view đang chạy bản cũ, chưa có API sản xuất hàng loạt. Đóng AIR3view đang chạy rồi mở lại bản mới.');
    throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail));
  }
  return body;
}

const stateName:Record<string,string>={pending:'Chờ',queued:'Trong hàng đợi',running:'Đang chạy',completed:'Hoàn tất',failed:'Lỗi',cancelled:'Đã hủy',deleted:'Dự án đã xóa'};
const rowFrom=(value:{url:string;title?:string;settings?:Record<string,any>;row?:number}):Row=>({url:value.url,title:value.title||'',settings:value.settings||{},settingsText:JSON.stringify(value.settings||{},null,2),row:value.row});

export function BatchWorkspace({projects,onBack,onOpen}:{projects:Project[];onBack:()=>void;onOpen:(id:string)=>void}){
  const [batches,setBatches]=useState<Batch[]>([]),[selected,setSelected]=useState('');
  const [name,setName]=useState('Lô video YouTube'),[raw,setRaw]=useState(''),[rows,setRows]=useState<Row[]>([]),[preview,setPreview]=useState<Preview[]>([]);
  const [settings,setSettings]=useState<Record<string,any>>({}),[profile,setProfile]=useState(''),[advanced,setAdvanced]=useState('');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [storage,setStorage]=useState<{default:string}>({default:''});
  const [exportTarget,setExportTarget]=useState<string|null|undefined>(undefined),[exportMode,setExportMode]=useState<'single'|'parts'>('single'),[exportCount,setExportCount]=useState(2),[exportDirectory,setExportDirectory]=useState(''),[exportBusy,setExportBusy]=useState(false);
  const current=batches.find(x=>x.id===selected);
  const set=(key:string,value:any)=>setSettings(s=>({...s,[key]:value}));
  const refresh=async()=>{const list=await request<Batch[]>('/batches');setBatches(list);setSelected(id=>id||list[0]?.id||'');};
  useEffect(()=>{let active=true,initialized=false,loading=false;
    const load=async()=>{if(loading)return;loading=true;try{
      const [defaults,list]=await Promise.all([request<{settings:Record<string,any>;source_project_id:string|null}>('/batches/defaults'),request<Batch[]>('/batches')]);
      if(!active)return;setSettings(defaults.settings);setProfile(defaults.source_project_id||'');setBatches(list);setSelected(list[0]?.id||'');setError('');initialized=true;
    }catch(e){if(active)setError(String(e));}finally{loading=false;}};
    void load();const id=window.setInterval(()=>{if(!initialized){void load();return;}request<Batch[]>('/batches').then(list=>{if(active)setBatches(list);}).catch(e=>{if(active){initialized=false;setError(String(e));}});},2000);
    return()=>{active=false;clearInterval(id);};},[]);
  useEffect(()=>setAdvanced(JSON.stringify(settings,null,2)),[settings]);
  useEffect(()=>{request<{default:string}>('/export/storage').then(setStorage).catch(e=>setError(String(e)));},[]);
  const openExport=(item?:Item)=>{const source=projects.find(p=>p.id===item?.project_id)?.settings||settings;setExportMode(source.export_mode==='parts'?'parts':'single');setExportCount(source.export_part_count||2);setExportDirectory(source.export_directory||(source.export_drive?`${source.export_drive}\\AIR3view Exports`:''));setExportTarget(item?.id||null);};
  const submitExport=async()=>{if(!current||exportTarget===undefined)return;setExportBusy(true);setError('');try{
    await request('/batches/'+current.id+'/export',{method:'POST',body:JSON.stringify({item_id:exportTarget,export_mode:exportMode,export_part_count:exportCount,export_directory:exportDirectory})});
    setExportTarget(undefined);setNotice(exportTarget?'Đã đưa video vào hàng đợi xuất.':'Đã đưa cả lô vào hàng đợi xuất.');await refresh();
  }catch(e){setError(String(e));}finally{setExportBusy(false);}};
  const applyProfile=(id:string)=>{setProfile(id);const project=projects.find(p=>p.id===id);if(project)setSettings({...structuredClone(project.settings),title:''});else request<{settings:Record<string,any>}>('/batches/defaults').then(x=>setSettings({...x.settings,voice_reference:''})).catch(e=>setError(String(e)));};
  const addManual=()=>{const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return;setRows(old=>[...old,...lines.map(url=>rowFrom({url}))]);setRaw('');setPreview([]);};
  const patchRow=(index:number,patch:Partial<Row>)=>{setRows(old=>old.map((r,i)=>i===index?{...r,...patch}:r));setPreview([]);};
  const importExcel=async(file:File)=>{setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const imported=await request<Row[]>('/batches/import-excel',{method:'POST',body:form});setRows(old=>[...old,...imported.map(rowFrom)]);setPreview([]);setNotice(`Đã đọc ${imported.length} dòng từ Excel.`);}catch(e){setError(String(e));}finally{setBusy(false);}};
  const submittedRows=()=>rows.map((r,i)=>{let override:Record<string,any>;try{override=JSON.parse(r.settingsText||'{}');if(!override||Array.isArray(override)||typeof override!=='object')throw 0;}catch{throw new Error(`Dòng ${i+1}: cấu hình riêng phải là JSON object.`);}return {url:r.url,title:r.title,settings:override};});
  const validate=async()=>{setError('');try{const result=await request<Preview[]>('/batches/preview',{method:'POST',body:JSON.stringify({items:submittedRows(),settings})});setPreview(result);return result;}catch(e){setError(String(e));return null;}};
  const start=async()=>{setBusy(true);setError('');try{
    const checked=await validate();if(!checked||checked.some(r=>!r.valid))throw new Error('Sửa các URL lỗi trong bảng trước khi chạy.');
    const submitted=submittedRows();
    const result=await request<Batch>('/batches',{method:'POST',body:JSON.stringify({name,items:submitted,settings,source_project_id:profile||null})});
    setRows([]);setPreview([]);setSelected(result.id);await refresh();setNotice('Đã đưa lô vào hàng đợi nền.');
  }catch(e){setError(String(e));}finally{setBusy(false);}};
  const control=async(action:'pause'|'resume'|'cancel'|'cancel_item'|'retry',item_id?:string)=>{setError('');try{await request('/batches/'+selected+'/control',{method:'POST',body:JSON.stringify({action,item_id})});await refresh();}catch(e){setError(String(e));}};
  return <section className="batch-workspace">
    <div className="batch-heading"><button className="secondary" onClick={onBack}><ArrowLeft size={15}/> Workspace</button><div><h1>Sản xuất video hàng loạt</h1><p>Nạp URL, chốt cấu hình rồi để AIR3view xử lý nền theo từng dự án.</p></div></div>
    {error&&<div className="batch-alert" role="alert">{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="batch-notice">{notice}</div>}
    <div className="batch-columns"><div className="batch-panel"><h2>Tạo lô mới</h2><label>Tên lô<input value={name} maxLength={180} onChange={e=>setName(e.target.value)}/></label><label>URL YouTube, mỗi dòng một link<textarea rows={4} value={raw} placeholder="https://www.youtube.com/watch?v=…" onChange={e=>setRaw(e.target.value)}/></label><div className="batch-actions"><button className="secondary" onClick={addManual} disabled={!raw.trim()}><Plus size={14}/> Thêm danh sách</button><label className="batch-file"><Upload size={14}/> Nhập Excel .xlsx<input type="file" accept=".xlsx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void importExcel(file);e.target.value='';}}/></label><a className="secondary" href="/api/batches/template" download><FileSpreadsheet size={14}/> Tải Excel mẫu</a></div>
      <h3>Cấu hình chung</h3><p className="batch-hint">Chọn một dự án làm mẫu để dùng toàn bộ setting và giọng mẫu của dự án đó. AIR3view lưu riêng cấu hình cho từng video khi bắt đầu.</p><label>Áp dụng cấu hình từ dự án<select value={profile} onChange={e=>applyProfile(e.target.value)}><option value="">Mặc định hiện tại</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      <div className="batch-settings"><label>Chế độ<select value={settings.editorial_mode||'standard'} onChange={e=>setSettings(previous=>({...previous,editorial_mode:e.target.value,production_workflow:'plan_first',narration_style:'storytelling',opening_delay:0,...(e.target.value==='reaction_cops'?{hook_enabled:false}:{})}))}><option value="standard">Kể tình huống</option><option value="reaction_cops">Reaction COPS</option></select></label><label>AI provider<select value={settings.provider||'codex'} onChange={e=>set('provider',e.target.value)}><option value="codex">Codex</option><option value="openai">OpenAI API</option><option value="gemini">Gemini API</option></select></label><label>Model<input value={settings.model||''} onChange={e=>set('model',e.target.value)} placeholder="Model đã cấu hình"/></label><label>Thời lượng mong muốn (phút, 0 = nguồn)<input type="number" min="0" max="30" step="0.5" value={(settings.summary_seconds||0)/60} onChange={e=>set('summary_seconds',Number(e.target.value)*60)}/></label>{settings.editorial_mode==='reaction_cops'?<label>Số COMMENTARY<input type="number" min="1" max="10" value={settings.reaction_commentary_count??5} onChange={e=>set('reaction_commentary_count',Number(e.target.value))}/></label>:<label>Tỉ lệ thoại gốc (%)<input type="number" min="10" max="100" value={Math.round((settings.original_dialogue_ratio??.15)*100)} onChange={e=>set('original_dialogue_ratio',Number(e.target.value)/100)}/></label>}<label>Giọng đọc<select value={settings.tts_provider||'vieneu'} onChange={e=>set('tts_provider',e.target.value)}><option value="vieneu">VieNeu SDK</option><option value="omnivoice">OmniVoice</option></select></label><label>Tốc độ giọng<input type="number" min="0.5" max="1.5" step="0.05" value={settings.voice_speed??1} onChange={e=>set('voice_speed',Number(e.target.value))}/></label><label>Chế độ xuất<select value={settings.export_mode||'single'} onChange={e=>set('export_mode',e.target.value)}><option value="single">Một video</option><option value="parts">Chia phần</option></select></label>{settings.export_mode==='parts'&&<label>Số phần<input type="number" min="2" max="100" value={settings.export_part_count??2} onChange={e=>set('export_part_count',Number(e.target.value))}/></label>}<label className="batch-check"><input type="checkbox" checked={!!settings.hook_enabled} onChange={e=>set('hook_enabled',e.target.checked)}/> Bật hook</label><label className="batch-check"><input type="checkbox" checked={!!settings.subtitles} onChange={e=>set('subtitles',e.target.checked)}/> Phụ đề</label></div>
      <ExportDirectoryPicker directory={settings.export_directory||(settings.export_drive?`${settings.export_drive}\\AIR3view Exports`:'')} defaultDirectory={storage.default} onChange={directory=>setSettings(previous=>({...previous,export_directory:directory,export_drive:''}))}/>
      <details className="batch-advanced"><summary>Giọng, âm thanh, phụ đề, bố cục và rules</summary>
        <div className="batch-settings">
          <label>Ngôn ngữ<select value={settings.language||'Vietnamese'} onChange={e=>set('language',e.target.value)}><option value="Vietnamese">Tiếng Việt</option><option value="English">English</option><option value="Chinese">中文</option></select></label>
          <label>Cách phân tích<select value={settings.analysis_workflow||'efficient'} onChange={e=>set('analysis_workflow',e.target.value)}><option value="efficient">Tiết kiệm</option><option value="detailed">Chi tiết</option></select></label>
          <label>Giọng VieNeu<input value={settings.vieneu_voice||''} placeholder="Để trống dùng giọng mặc định" onChange={e=>set('vieneu_voice',e.target.value)}/></label>
          <label>Thiết bị VieNeu<select value={settings.vieneu_device||'cpu'} onChange={e=>set('vieneu_device',e.target.value)}><option value="cpu">CPU</option><option value="auto">Tự động</option><option value="cuda">CUDA</option></select></label>
          <label>Kiểu giọng<select value={settings.voice_mode||'design'} onChange={e=>set('voice_mode',e.target.value)}><option value="design">Giọng thiết kế</option><option value="clone">Theo giọng mẫu</option></select></label>
          <label>Âm lượng video gốc (%)<input type="number" min="0" max="200" value={Math.round((settings.original_volume??1)*100)} onChange={e=>set('original_volume',Number(e.target.value)/100)}/></label>
          <label>Tiếng gốc dưới voice AI (%)<input type="number" min="0" max="100" value={Math.round((settings.duck_volume??.15)*100)} onChange={e=>set('duck_volume',Number(e.target.value)/100)}/></label>
          <label>Âm lượng giọng AI (%)<input type="number" min="0" max="200" value={Math.round((settings.voice_volume??1)*100)} onChange={e=>set('voice_volume',Number(e.target.value)/100)}/></label>
          <label>Vị trí phụ đề<select value={settings.subtitle_position||'inside'} onChange={e=>set('subtitle_position',e.target.value)}><option value="inside">Trên video</option><option value="below">Bên dưới video</option></select></label>
          <label>Lề dưới phụ đề (px)<input type="number" min="0" max="200" value={settings.subtitle_bottom_margin??10} onChange={e=>set('subtitle_bottom_margin',Number(e.target.value))}/></label>
          <label>Làm mờ phụ đề gốc (%)<input type="number" min="5" max="50" value={settings.source_subtitle_blur_height??22} onChange={e=>set('source_subtitle_blur_height',Number(e.target.value))}/></label>
          <label>Nền<select value={settings.background_mode||'blur'} onChange={e=>set('background_mode',e.target.value)}><option value="blur">Nền mờ</option><option value="color">Màu cố định</option></select></label>
          <label>Khung hình<select value={settings.fit||'cover'} onChange={e=>set('fit',e.target.value)}><option value="cover">Phủ khung</option><option value="contain">Giữ toàn khung</option></select></label>
          <label>Bộ mã hóa<select value={settings.render_encoder||'auto'} onChange={e=>set('render_encoder',e.target.value)}><option value="auto">Tự động</option><option value="cpu">CPU</option><option value="nvenc">NVENC</option></select></label>
          <label className="batch-check"><input type="checkbox" checked={!!settings.subtitle_highlight} onChange={e=>set('subtitle_highlight',e.target.checked)}/> Highlight từ phụ đề</label>
          <label className="batch-check"><input type="checkbox" checked={!!settings.source_subtitle_blur} onChange={e=>set('source_subtitle_blur',e.target.checked)}/> Làm mờ phụ đề nguồn</label>
          <label className="batch-check"><input type="checkbox" checked={!!settings.review_enabled} onChange={e=>set('review_enabled',e.target.checked)}/> Bật lượt AI kiểm tra</label>
        </div>
        <label>Rule viết kịch bản<textarea rows={4} value={settings.draft_rule||''} onChange={e=>set('draft_rule',e.target.value)}/></label>
        <label>Rule kiểm tra<textarea rows={3} value={settings.review_rule||''} onChange={e=>set('review_rule',e.target.value)}/></label>
        <label>Rule tóm tắt<textarea rows={3} value={settings.summary_rule||''} onChange={e=>set('summary_rule',e.target.value)}/></label>
      </details>
      <details className="batch-advanced"><summary>Cấu hình đầy đủ · tất cả setting của một video</summary><p className="batch-hint">Có thể chỉnh những trường nâng cao trong JSON rồi bấm Áp dụng. Bản này được kiểm tra trước khi tạo lô.</p><textarea rows={10} value={advanced} onChange={e=>setAdvanced(e.target.value)}/><button className="secondary" onClick={()=>{try{const value=JSON.parse(advanced);if(!value||Array.isArray(value)||typeof value!=='object')throw 0;setSettings(value);setNotice('Đã áp dụng cấu hình đầy đủ.');}catch{setError('Cấu hình đầy đủ phải là JSON object hợp lệ.');}}}>Áp dụng cấu hình đầy đủ</button></details>
      <div className="batch-create-actions"><button className="secondary" disabled={!rows.length||busy} onClick={()=>void validate()}><RefreshCw size={14}/> Kiểm tra URL</button><button className="primary" disabled={!rows.length||busy} onClick={()=>void start()}>{busy?<LoaderCircle size={15} className="spin"/>:<Play size={15}/>} Bắt đầu {rows.length} video</button></div>
    </div>
    <div className="batch-panel"><h2>Danh sách chờ <span>{rows.length}</span></h2>{!rows.length?<p className="batch-empty">Nhập URL hoặc Excel để thêm video.</p>:<div className="batch-row-list">{rows.map((row,i)=><div className="batch-draft" key={i}><div className="batch-draft-top"><b>{i+1}</b><span className={preview[i]?.valid===false?'invalid':'valid'}>{preview[i]?.valid===false?preview[i].error:preview[i]?.valid?'Hợp lệ':'Chưa kiểm tra'}</span><button title="Bỏ video" onClick={()=>{setRows(old=>old.filter((_,j)=>j!==i));setPreview([]);}}><X size={14}/></button></div><input aria-label={'URL video '+(i+1)} value={row.url} onChange={e=>patchRow(i,{url:e.target.value})}/><input aria-label={'Tên video '+(i+1)} placeholder="Tên dự án (tùy chọn)" value={row.title} onChange={e=>patchRow(i,{title:e.target.value})}/><details><summary>Cấu hình riêng</summary><textarea aria-label={'Cấu hình video '+(i+1)} rows={4} value={row.settingsText} onChange={e=>patchRow(i,{settingsText:e.target.value})}/><small>Ví dụ: {`{"summary_seconds":120,"hook_enabled":false}`}</small></details></div>)}</div>}</div></div>
    <div className="batch-panel batch-monitor">
      <div className="batch-monitor-head"><h2>Theo dõi lô</h2><select aria-label="Chọn lô" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Chọn lô</option>{batches.map(batch=><option value={batch.id} key={batch.id}>{batch.name} · {new Date(batch.created*1000).toLocaleDateString()}</option>)}</select>{current&&<><button className="secondary" disabled={current.state!=='running'} onClick={()=>void control('pause')}><Pause size={14}/> Tạm dừng</button><button className="secondary" disabled={current.state!=='paused'} onClick={()=>void control('resume')}><Play size={14}/> Tiếp tục</button><button className="secondary" disabled={!['running','paused'].includes(current.state)} onClick={()=>void control('cancel')}>Hủy lô</button><button className="secondary" disabled={!current.items.length||current.items.some(item=>item.state!=='completed'||['queued','running'].includes(item.export_state))} onClick={()=>openExport()}><Download size={14}/> Xuất toàn bộ</button></>}</div>
      {current?<><p className="batch-hint">{current.items.filter(x=>x.state==='completed').length}/{current.items.length} hoàn tất · {current.items.filter(x=>x.state==='running').length} đang chạy · {current.items.filter(x=>x.state==='failed').length} lỗi · Trạng thái lô: {current.state}. Tạm dừng chỉ ngăn video mới bắt đầu; video đang chạy vẫn hoàn tất.</p>
        <div className="batch-table-wrap"><table><thead><tr><th>#</th><th>Video</th><th>Trạng thái</th><th>Tiến trình</th><th>Kết quả / thao tác</th></tr></thead><tbody>{current.items.map(item=><tr key={item.id}>
          <td>{item.position}</td><td><strong>{item.title}</strong><small>{item.url}</small></td>
          <td><span className={'batch-state '+item.state}>{item.state==='pending'&&item.attempts>0?'Chờ thử lại':stateName[item.state]||item.state}</span>
            {item.attempts>0&&<small className="batch-retry">{item.state==='pending'&&item.ready_at>0
              ?current.state==='paused'?`Đã tạm dừng · lượt ${item.attempts}/${item.retry_limit}`:`Tự thử lại lượt ${item.attempts}/${item.retry_limit} sau ${Math.max(0,Math.ceil(item.ready_at-Date.now()/1000))}s`
              :item.state==='failed'&&item.retry_limit>0&&item.attempts>=item.retry_limit?`Đã hết ${item.retry_limit} lượt tự thử lại`:`Đã tự thử lại ${item.attempts} lượt`}</small>}
            {item.error&&<small className="batch-error">{item.error}</small>}</td>
          <td><div className="batch-meter"><i style={{width:Math.min(100,item.progress)+'%'}}/></div><small>{Math.round(item.progress)}% · {item.message}</small></td>
          <td>{item.state!=='deleted'&&<button className="secondary" onClick={()=>onOpen(item.project_id)}><FolderOpen size={13}/> Mở dự án</button>}
            {item.state==='completed'&&<button className="secondary" disabled={['queued','running'].includes(item.export_state)} onClick={()=>openExport(item)}><Download size={13}/> Xuất video</button>}
            {item.export_state&&<small className={item.export_state==='failed'?'batch-error':'batch-retry'}>{item.export_state==='completed'?`Đã lưu: ${item.export_folder}`:item.export_state==='failed'?`Xuất lỗi: ${item.export_error}`:`Đang xuất ${Math.round(item.export_progress)}% · ${item.export_message}`}</small>}
            {['pending','queued','running'].includes(item.state)&&<button className="secondary" onClick={()=>void control('cancel_item',item.id)}>Hủy video</button>}
            {['failed','cancelled'].includes(item.state)&&<button className="secondary" onClick={()=>void control('retry',item.id)}><RefreshCw size={13}/> Thử lại</button>}
          </td></tr>)}</tbody></table></div></>:<p className="batch-empty">Chưa có lô video nào.</p>}
    </div>
    {exportTarget!==undefined&&<div className="batch-export-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!exportBusy)setExportTarget(undefined);}}><section className="batch-export-dialog" role="dialog" aria-modal="true" aria-label="Xuất video lô"><h2>{exportTarget?'Xuất video':'Xuất toàn bộ video trong lô'}</h2><p>MP4, SRT và ASS sẽ được lưu chung trong thư mục theo tên và ngày xuất.</p><label>Kiểu xuất<select value={exportMode} onChange={e=>setExportMode(e.target.value as 'single'|'parts')}><option value="single">Một video hoàn chỉnh</option><option value="parts">Chia đều thành các phần</option></select></label>{exportMode==='parts'&&<label>Số phần mỗi video<input type="number" min={2} max={100} value={exportCount} onChange={e=>setExportCount(Number(e.target.value))}/></label>}<ExportDirectoryPicker directory={exportDirectory} defaultDirectory={storage.default} onChange={setExportDirectory} disabled={exportBusy}/><div className="batch-export-actions"><button className="secondary" disabled={exportBusy} onClick={()=>setExportTarget(undefined)}>Hủy</button><button className="primary" disabled={exportBusy||(exportMode==='parts'&&(exportCount<2||exportCount>100))} onClick={()=>void submitExport()}>{exportBusy?'Đang tạo tác vụ…':'Bắt đầu xuất'}</button></div></section></div>}
  </section>;
}
